### ISSUE TITLE
Yarn-link-ing React-UI-Core produces error when used by Ag.js

### ISSUE THREAD

**Issue by cwklausing** [rentpath/react-ui#421]
### To Reproduce Issue
1. Follow steps in "working locally" in the README for `react-ui-core`
2. Link `react-ui-core` in ag.js
2. Load SRP or PDP in Ag.js

### Potential Cause
I was able to eliminate the error by removing the LazyLoad component from PhotoCarousel [here](https://github.com/rentpath/react-ui/blob/master/packages/react-ui-core/src/Carousel/PhotoCarousel.js#L108). However, haven't determined what within the LazyLoad is causing the error in the first place.

**Comment by tadjohnston** [comment]
This is related to out of sync issues with react and react-dom with this package dependencies and ag.js (or any other repo) dependencies using the same when linking.  You _must_ make sure if you're running the same exact versions of both react and react-dom in both.
